<?php

/**
 * @file
 */

require_once('includes/postgis.feeds.inc');
require_once('includes/postgis.field.formatter.inc');
require_once('includes/postgis.field.inc');
require_once('includes/postgis.field.widget.inc');
require_once('includes/postgis.geometry.inc');
require_once('includes/postgis.openlayers.inc');

define('POSTGIS_DEFAULT_SRID', 4326);

/**
 * Implements hook_ctools_plugin_api().
 *
 * Required for OpenLayers integration.
 */
function postgis_ctools_plugin_api($module, $api) {
  return array('version' => 1);
}
